pipeline {
  agent any 
    stages {
      stage(build) {
        steps {
          sh 'maven -version'
          sh 'java -version'
          sh 'cd spring-boot-app && mvn clean compile && mvn clean package'
        }






        
      }
    }
  


  
}
