pipeline {
  agent any 
    stages {
      stage(checkout) {
        steps {
          sh 'echo passed'
        }
      }
      stage('build and test') {
        steps {
          sh 'cd spring-boot-app && mvn clean package'
        }
      }






        
      }
    }
  


  

