pipeline {
  agent any 
    stages {
      stage(build) {
        steps {
          sh 'mvn -version'
          sh 'java -version'
          sh 'cd spring-boot-app && mvn clean compile'
        }
      stage(execute unit test cases) {
        steps {
          sh 'cd spring-boot-app && mvn clean test'
        }
      }






        
      }
    }
  


  
}
